package.json: change "filename" into "main"
"main" is the official key to refer to the package entrypoint, see https://docs.npmjs.com/files/package.json

In particular, without this modification the package does not load in node (latest verisons) nor browserify.

```
> (adv-ui)[vperron@M]<~/dev/adv-ui> iopm install floatthead --save
> (adv-ui)[vperron@M]<~/dev/adv-ui> node
> require('floatthead')
Error: Cannot find module 'floatthead'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:132:27)
```

It works very well after this change.